# Response messages
STORED_MSG = "STORED\r\n"
NOT_STORED_MSG = "NOT_STORED\r\n"
NOT_FOUND_MSG = "NOT_FOUND\r\n"
EXISTS_MSG = "EXISTS\r\n"
INVALID_COMMAND_NAME_MSG = "ERROR\r\n"
END_MSG = "END\r\n"

# Expiration date
SECONDS_PER_DAY = 60*60*24
UNIX_TIME = Time.new(1970,1,1)

MAX_KEY_LENGTH = 250
MAX_VALUE_LENGTH = (2 ** 20) - 1 # 1MB
MAX_CAS_KEY = (2 ** 64) - 1 # 64-bit unsigned int
MAX_CACHE_ITEMS = 64